In [3]:
import numpy as np
from keras import backend as K

In [4]:
a = K.ones((3,4))
b = K.ones((4,5))
c = K.dot(a, b)
print(c.shape)

(3, 5)


In [69]:
n_batch = X.shape[0]
n_features = X.shape[1]
n_y = Y.shape[0]
n_first_layer = 2 
print(n_batch, n_y,n_first_layer,n_features)
X = np.hstack((np.ones((n_batch,1)),X))
X

3 3 2 2


array([[ 1.    ,  0.5403, -0.4161],
       [ 1.    , -0.99  , -0.6536],
       [ 1.    ,  0.2837,  0.9602]])

In [70]:
W1 = np.random.randn(n_first_layer,n_features) * 0.01
print("W1\n", W1)

W1
 [[-0.00145311 -0.00857686 -0.00391022]
 [-0.01133853  0.01292411 -0.00620124]]


In [11]:
def sigmoid(x):
    return 1 / (1 + np.e ** -x)

total_cost = -9999

In [31]:
np.dot(W1,X)

array([[-0.02605248,  0.00280253],
       [-0.00950785,  0.0134963 ],
       [-0.01780765,  0.02687232],
       [ 0.00526706, -0.0105653 ]])

In [15]:
Z1 = np.dot(W1,X) + b1
A1 = np.tanh(Z1)
print(Z1)
print(A1)

[[-0.00256086 -0.00218237]
 [ 0.00379836  0.00675179]
 [ 0.01159849  0.01425437]
 [-0.00856304 -0.00175203]]
[[-0.00256086 -0.00218237]
 [ 0.00379834  0.00675169]
 [ 0.01159797  0.01425341]
 [-0.00856283 -0.00175203]]


In [ ]:
# W2 = np.random.randn(n_y,n_h) * 0.01 #1x4
# b2 = np.zeros(shape=(n_y, 1))#1x1